In [2]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)



[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [ ]:
import numpy as np
list=[]
list=[]
num=5
for i in range(0,num):
    list1=int(input())
    list.append(list1)
print(list)
for j in range(0,num):
    list2=int(input())
    list1.append(list2)
    print(list1)
arr=np.array(list)
print(arr)
arr1=np.array(list1)
print(arr1)
arr2=np.concatenate((arr,arr1))
print(arr2)
print(np.sort(arr2))

question 3

In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
type(x)
x.shape


In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
x.size

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Convert 1D array to a 2D numpy array of 2 rows and 3 columns
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)


In [ ]:
x1 = np.array([1, 2, 3, 4, 5])
 x2 = np.array([5, 4, 3])
x1_new = x1[:, np.newaxis]
x1_new + x2

In [ ]:
import numpy as np 
a = np.array([[1,2],[3,4]]) 
 
print (a) 
  
b = np.array([[5,6],[7,8]]) 
 
print (b) 

c = np.vstack((a,b)) 
print (c)

In [14]:
import numpy as np 
a = np.array([[1,2],[3,4]]) 
 
print (a) 
  
b = np.array([[5,6],[7,8]]) 
 
print (b) 

c = np.hstack((a,b)) 
print (c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import pandas as pd 
data={
    'id':[1,2,3,4,5],
    'group':['abc','pqr','xyz','abc','mno'],
    'team':['team A','team B','team D','team A','team A'] 
}
df=pd.DataFrame(data)
print(df)
unique_values=df['team'].nunique()
print()
print("unique values in team are:",unique_values)
            


In [ ]:
df['group'].unique()